[role="pagenumrestart"]

== "Equal-for-All" Mining Proposal

[[Concept]]
=== CONCEPT

To participate in mining the following criteria is enforced:

* 1 personal blockstack ID = 1 mining node (you might have multiple IDs linked to you but all these IDs relate to 1 personal blockstack ID / address

*That’s it…* Everyone can easily participate if they have a blockstack ID.

“*Equal-for-all*" mining opportunity would work as such:

. Each miner would run a full node of blockstack and install the mining software
.. Configuration of the mining software would include:
... *BTC address* – for staking BTC and receiving BTC
... *Blockstack ID* (for validation)
... *Deviation %* (+ or -) above the set BTC fee per block (limited to x% : potentially -5% to +5%)
.... This is the only variable that a miner can adjust to influence their winning chances
. Blockstack will publish the total number of BTC needed to mine a block e.g. 1 BTC
.. *TOTAL BTC* = 1
. Blockstack will publish the total number of active miners e.g. 100
.. *TOTAL MINERS* = 100
. When the process of mining a block starts the code will read (2) and (3) to determine the amount of BTC to be committed as a transaction fee.
.. 100 *TOTAL MINERS* {3a} x ( _X_ *Transaction Fee* {4} + 5% *DEVIATION %* {1aiii} ) = 1 *TOTAL BTC* {2a}
... _X_ (the transaction fee) is calculated for each miner and only differs slightly based on the choice that the miner has made to slightly discount the fee (slightly less chance of winning) or slightly increase the fee (slightly increased chance of winning).

=== REASONING

Using bitcoin as an example, everyday folks cannot realistically hope to win a block insertion by running their own mining operation without expending a small fortune to bolster their computing power. Their only option to take part in mining is to join a pool… 

What if we make mining an equal opportunity for all? Blockchain, as a distributed technology, with open-source code lends itself towards this very concept. Make it available to all, show everyone that it is a reliable, fair and equal system where the rules apply equally to everyone, … no exceptions. 
rmine an optimal amount of BTC to stake then we get in to the space where “programmers” or “vigilant” miners have an advantage over others because they can automatically (or manually) adjust their BTC stake to increase their chances of winning. I understand that increasing a BTC stake to win a block may make it unfeasible financially but that is just another variable that a miner has to consider before making their choice of the amount of BTC to stake. This again leads to giving programmers or vigilant / attentive miners an advantage over others.

The idea is to have an easy / fair mining solution that can be undertaken by all folks (programmers, analysts, moms and dads, students, unbanked, clueless …) With this approach we can easily reach a critical mass of miners to fully secure the network. Since everyone has a similar chance of winning there is less chance of them “giving up” mining because they never win (people like to win!) and large corporations or pools cannot monopolize mining. As the number of miners increases the amount of BTC that you stake is proportionately decreased. 

This will allow a miner to set up their operation and leave it running for as long as they want without having to constantly monitor it and the markets around it. 
